# RootForge OS — Calamares finished module
# Victorious Framework | Origin Source Labs

---
restartNowEnabled:  true
restartNowChecked:  true
restartNowCommand:  "systemctl reboot"
notifyOnFinished:   false
