# RootForge OS — Calamares users module
# Victorious Framework | Origin Source Labs

---
userGroup:    users
defaultGroups:
  - adm
  - cdrom
  - sudo
  - dip
  - plugdev
  - kvm
  - docker
  - lpadmin

# Autologin is off by default — this is a dev box, not a kiosk
autologinGroup: autologin
doAutologin:    false

sudoersGroup:         sudo
setRootPassword:      true
doReusePassword:      false
passwordRequirements:
  minLength: 6

avatarFilePath: ~/.face
