# RootForge OS — Calamares welcome module
# Victorious Framework | Origin Source Labs

---
showSupportUrl:    true
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
  requiredStorage:    20.0
  requiredRam:        2.0
  checkHasInternetNoCheckForUpdates: false
  checkInternetUrl:   "https://example.com"
  check:
    - storage
    - ram
    - power
    - internet
  required:
    - storage
    - ram
